<a href="https://colab.research.google.com/github/Nonyed/sit774-10.3hd-awesome-canvas-app/blob/main/SIT719_Task_2_1_Basic_Python_Scripting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url, header=None)

iris.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [3]:
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

print("Column names:")
print(iris.columns)

iris.head()

Column names:
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
print("Are there any missing values (True/False)?")
print(iris.isnull().values.any())

print("\nMissing values per column:")
print(iris.isnull().sum())

Are there any missing values (True/False)?
False

Missing values per column:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

In [5]:
iris.loc[10:29, 'petal_length'] = np.nan

iris.loc[10:29, ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']]

    sepal_length  sepal_width  petal_length  petal_width        class
10           5.4          3.7           NaN          0.2  Iris-setosa
11           4.8          3.4           NaN          0.2  Iris-setosa
12           4.8          3.0           NaN          0.1  Iris-setosa
13           4.3          3.0           NaN          0.1  Iris-setosa
14           5.8          4.0           NaN          0.2  Iris-setosa
15           5.7          4.4           NaN          0.4  Iris-setosa
16           5.4          3.9           NaN          0.4  Iris-setosa
17           5.1          3.5           NaN          0.3  Iris-setosa
18           5.7          3.8           NaN          0.3  Iris-setosa
19           5.1          3.8           NaN          0.3  Iris-setosa
20           5.4          3.4           NaN          0.2  Iris-setosa
21           5.1          3.7           NaN          0.4  Iris-setosa
22           4.6          3.6           NaN          0.2  Iris-setosa
23           5.1          3.3           NaN          0.5  Iris-setosa
24           4.8          3.4           NaN          0.2  Iris-setosa
25           5.0          3.0           NaN          0.2  Iris-setosa
26           5.0          3.4           NaN          0.4  Iris-setosa
27           5.2          3.5           NaN          0.2  Iris-setosa
28           5.2          3.4           NaN          0.2  Iris-setosa
29           4.7          3.2           NaN          0.2  Iris-setosa

In [6]:
print("Missing values per column after setting NaN:")
print(iris.isnull().sum())

print("\nNumber of missing values in 'petal_length' only:")
print(iris['petal_length'].isnull().sum())

Missing values per column after setting NaN:
sepal_length     0
sepal_width      0
petal_length    20
petal_width      0
class            0
dtype: int64

Number of missing values in 'petal_length' only:
20

In [7]:
iris['petal_length'].fillna(10.0, inplace=True)

print("Missing values per column after filling NaN with 10.0:")
print(iris.isnull().sum())

iris.loc[10:29, ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']]

Missing values per column after filling NaN with 10.0:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

/tmp/ipython-input-3246371585.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris['petal_length'].fillna(10.0, inplace=True)

    sepal_length  sepal_width  petal_length  petal_width        class
10           5.4          3.7          10.0          0.2  Iris-setosa
11           4.8          3.4          10.0          0.2  Iris-setosa
12           4.8          3.0          10.0          0.1  Iris-setosa
13           4.3          3.0          10.0          0.1  Iris-setosa
14           5.8          4.0          10.0          0.2  Iris-setosa
15           5.7          4.4          10.0          0.4  Iris-setosa
16           5.4          3.9          10.0          0.4  Iris-setosa
17           5.1          3.5          10.0          0.3  Iris-setosa
18           5.7          3.8          10.0          0.3  Iris-setosa
19           5.1          3.8          10.0          0.3  Iris-setosa
20           5.4          3.4          10.0          0.2  Iris-setosa
21           5.1          3.7          10.0          0.4  Iris-setosa
22           4.6          3.6          10.0          0.2  Iris-setosa
23           5.1          3.3          10.0          0.5  Iris-setosa
24           4.8          3.4          10.0          0.2  Iris-setosa
25           5.0          3.0          10.0          0.2  Iris-setosa
26           5.0          3.4          10.0          0.4  Iris-setosa
27           5.2          3.5          10.0          0.2  Iris-setosa
28           5.2          3.4          10.0          0.2  Iris-setosa
29           4.7          3.2          10.0          0.2  Iris-setosa